### ISSUE TITLE
Chrome?

### ISSUE THREAD

**Issue by mmp7700** [CodyHouse/cd-video-background-hero-changelog#1]
Are there any specific considerations for making this work right in Chrome? I see it working in Chrome on the demo site but I'm having trouble replicating. 

Thanks!

**Comment by claudia-romano** [comment]
Hi there, you will need to add the `muted` attribute to the video to make it autoplay in the background. You could check the attributes we use in the component demo code:
https://codyhouse.co/ds/components/app/video-background-hero

Cheers!

**Comment by mmp7700** [comment]
After digging into this, the issue was not with the CSS/HTML. Hints to others to check: check the mp4 encoding of your file. Chrome/Edge seem to only like h.264 mpeg encoding. 

Thanks Claudia!
