### ISSUE TITLE
Feedback/suggestion: good practice to have the possibility to trigger video on demand

### ISSUE THREAD

**Issue by Julianoe** [CodyHouse/cd-video-background-hero-changelog#2]
For a video background it's cool when you can have a button allowing to play the video for example to avoid burning through the data of users with low data plans. Also to be able to mute/play sound.

An example to illustrate the kind of thing I'm thinking about: https://hotel-etable.ch/
Would allow for a third option, between autoplay background and modal.

**Comment by claudia-romano** [comment]
Hi there, thanks for the suggestion. 

At the moment, we are not adding new features to the CodyHouse components as we are still evaluating the next steps for CodyHouse. You can read the reasons behind that here:
https://x.com/guerriero_se/status/1811761171180974478

**Comment by Julianoe** [comment]
Thanks for the answer. A shame I did not see that before checking out the product 😆
